---
- name: Remove WireGuard Configuration
  hosts: all
  become: true
  gather_facts: false
  tags: [remove-wg, wg]
  tasks:
    - name: Check confirmation for full cleanup
      ansible.builtin.fail:
        msg: "Full cleanup requires confirmation. Add -e full_cleanup=yes to proceed."
      when:
        - target is not defined
        - full_cleanup is not defined or full_cleanup != 'yes'

    - name: Find DN42 WireGuard configurations
      ansible.builtin.find:
        paths: /etc/wireguard
        patterns: "dn42_*.conf"
      register: wg_configs
      when: target is not defined

    - name: Set target WireGuard configuration
      ansible.builtin.set_fact:
        wg_targets: "{{ [{'path': '/etc/wireguard/' + target + '.conf'}] }}"
      when: target is defined

    - name: Set all WireGuard configurations
      ansible.builtin.set_fact:
        wg_targets: "{{ wg_configs.files }}"
      when: target is not defined

    - name: Stop and disable WireGuard services
      ansible.builtin.systemd:
        name: "wg-quick@{{ item.path | basename | splitext | first }}"
        state: stopped
        enabled: false
      loop: "{{ wg_targets }}"
      loop_control:
        label: "{{ item.path | basename }}"
      ignore_errors: true

    - name: Remove WireGuard configuration files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ wg_targets }}"
      loop_control:
        label: "{{ item.path | basename }}"

- name: Remove BIRD Configuration
  hosts: all
  become: true
  gather_facts: false
  tags: [remove-bird, bird]
  tasks:
    - name: Check confirmation for full cleanup
      ansible.builtin.fail:
        msg: "Full cleanup requires confirmation. Add -e full_cleanup=yes to proceed."
      when:
        - target is not defined
        - full_cleanup is not defined or full_cleanup != 'yes'

    - name: Stop and disable BIRD service (Full Cleanup)
      ansible.builtin.service:
        name: bird
        state: stopped
        enabled: false
      ignore_errors: true
      when: target is not defined

    - name: Remove BIRD peer configurations (Full Cleanup)
      ansible.builtin.file:
        path: /etc/bird/peers
        state: absent
      when: target is not defined

    - name: Remove BIRD node configurations (Full Cleanup)
      ansible.builtin.file:
        path: /etc/bird/nodes
        state: absent
      when: target is not defined

    - name: Recreate empty directories (Full Cleanup)
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: bird
        group: bird
        mode: '0755'
      loop:
        - /etc/bird/peers
        - /etc/bird/nodes
      when: target is not defined

    - name: Remove specific BIRD peer configuration
      ansible.builtin.file:
        path: "/etc/bird/peers/{{ target }}.conf"
        state: absent
      when: target is defined
      notify: Reload BIRD

  handlers:
    - name: Reload BIRD
      ansible.builtin.command: birdc configure
      ignore_errors: true
      changed_when: true
